services:
  mssql:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_COLLATION=SQL_Latin1_General_CP1_CS_AS
      - TZ=${TIMEZONE}
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${MSSQL_SA_PASSWORD}
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -d ${DB_NAME} -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - "1433:1433"
#    volumes:
#      - mssql:/var/opt/mssql

#volumes:
#  mssql:

